# Generated by Django 2.2.4 on 2019-09-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('f_publicacion', models.DateField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.Categoria')),
                ('Periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodista.Periodista')),
            ],
        ),
    ]
