# Generated by Django 2.2.4 on 2019-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_auto_20190914_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
