# Generated by Django 2.2.4 on 2019-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='default_img.png', upload_to='imagen_articulo'),
        ),
    ]
