# Generated by Django 2.2.4 on 2019-09-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0005_auto_20190914_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagen_articulo'),
        ),
    ]
