# Generated by Django 2.2.4 on 2019-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_auto_20190915_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='imagen_articulo'),
        ),
    ]
