# Generated by Django 2.2.4 on 2019-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0007_auto_20190916_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagen_articulo'),
        ),
    ]
